# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R5HkWGVLTHmmK1iD8Kn1ariy2qEpTrzw
"""

import streamlit as st
import numpy as np
import joblib
import os

# Load model
MODEL_PATH = os.path.join(os.path.dirname(__file__), "credit_card.pkl")
model = joblib.load(MODEL_PATH)

st.title("💳 Credit Card Fraud Detection System")

st.write("Enter transaction details below:")

# ----------------------------
# BASIC INPUTS (USER FRIENDLY)
# ----------------------------
time = st.number_input("Time (seconds)", value=0)
amount = st.number_input("Transaction Amount", value=0.0)

st.subheader("Advanced Features (Model Inputs)")

# ----------------------------
# V1 - V28 (MUST MATCH MODEL)
# ----------------------------
v = []

cols = st.columns(3)

for i in range(1, 29):
    col = cols[i % 3]
    val = col.number_input(f"V{i}", value=0.0)
    v.append(val)

# ----------------------------
# PREDICTION
# ----------------------------
if st.button("Check Fraud Risk"):

    features = np.array([[time, amount] + v])

    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][1]

    st.subheader("Result")

    if prediction == 1:
        st.error("🚨 FRAUD DETECTED")
    else:
        st.success("✅ LEGITIMATE TRANSACTION")

    st.write(f"Fraud Probability: {probability:.2%}")
    st.progress(float(probability))