# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R5HkWGVLTHmmK1iD8Kn1ariy2qEpTrzw
"""

import streamlit as st
import joblib
import numpy as np

# Load model
model = joblib.load("credit_fraud_model.pkl")

st.title("💳 Credit Card Fraud Detection System")
st.write("Enter transaction details to check if it is fraudulent.")

# ----------------------------
# USER INPUT (REALISTIC UI)
# ----------------------------

amount = st.number_input("Transaction Amount ($)", min_value=0.0, value=50.0)
time = st.number_input("Time (seconds since first transaction)", min_value=0, value=10000)

st.subheader("Advanced (Simulated Risk Features)")

col1, col2, col3 = st.columns(3)

with col1:
    risk1 = st.slider("Behavior Risk 1", -10.0, 10.0, 0.0)
    risk2 = st.slider("Behavior Risk 2", -10.0, 10.0, 0.0)
    risk3 = st.slider("Behavior Risk 3", -10.0, 10.0, 0.0)
    risk4 = st.slider("Behavior Risk 4", -10.0, 10.0, 0.0)
    risk5 = st.slider("Behavior Risk 5", -10.0, 10.0, 0.0)

with col2:
    risk6 = st.slider("Behavior Risk 6", -10.0, 10.0, 0.0)
    risk7 = st.slider("Behavior Risk 7", -10.0, 10.0, 0.0)
    risk8 = st.slider("Behavior Risk 8", -10.0, 10.0, 0.0)
    risk9 = st.slider("Behavior Risk 9", -10.0, 10.0, 0.0)
    risk10 = st.slider("Behavior Risk 10", -10.0, 10.0, 0.0)

with col3:
    risk11 = st.slider("Behavior Risk 11", -10.0, 10.0, 0.0)
    risk12 = st.slider("Behavior Risk 12", -10.0, 10.0, 0.0)
    risk13 = st.slider("Behavior Risk 13", -10.0, 10.0, 0.0)
    risk14 = st.slider("Behavior Risk 14", -10.0, 10.0, 0.0)
    risk15 = st.slider("Behavior Risk 15", -10.0, 10.0, 0.0)

# ----------------------------
# PREDICTION
# ----------------------------

if st.button("Check Fraud Risk"):

    # Build feature vector (match training order!)
    features = np.array([[
    time,
    amount,
    v1, v2, v3, v4, v5,
    v6, v7, v8, v9, v10,
    v11, v12, v13, v14, v15,
    v16, v17, v18, v19, v20,
    v21, v22, v23, v24, v25,
    v26, v27, v28
]])

    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][1]

    # ----------------------------
    # OUTPUT
    # ----------------------------

    st.subheader("Result")

    if prediction == 1:
        st.error("🚨 FRAUD DETECTED")
    else:
        st.success("✅ LEGITIMATE TRANSACTION")

    st.write(f"Fraud Probability: {probability:.2%}")

    # Risk meter
    st.progress(float(probability))